name: lint
on: [push, pull_request]

jobs:
  code_linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
          
      - name: Code formatting check with Black
        run: |
          python -m black --check --diff src/ tests/
          
      - name: Import sorting check with isort
        run: |
          python -m isort --check-only --diff src/ tests/
          
      - name: Linting with flake8
        run: |
          python -m flake8 src/ tests/ --max-line-length=100 --extend-ignore=E203,W503
          
      - name: Type checking with mypy
        run: |
          python -m mypy src/ --ignore-missing-imports
          
          

